### ISSUE TITLE
Invalid library name to import

### ISSUE THREAD

**Issue by AbsoluteGZ** [optuna/optuna-integration#137]
### Motivation

with optuna._imports.try_import() as _imports:
    import lightning.pytorch as pl
    from lightning.pytorch import LightningModule
    from lightning.pytorch import Trainer
    from lightning.pytorch.callbacks import Callback

### Suggestion

with optuna._imports.try_import() as _imports:
    import pytorch_lightning as pl
    from pytorch_lightning import LightningModule
    from pytorch_lightning import Trainer
    from pytorch_lightning.callbacks import Callback

**Comment by nzw0301** [comment]
I think you're using an old pytorch-lightning because it has renamed the package name as described in https://github.com/Lightning-AI/pytorch-lightning/discussions/16688. So optuna followed the change https://github.com/optuna/optuna/issues/4935.

**Comment by AbsoluteGZ** [comment]
Sorry, my bad(

**Comment by nzw0301** [comment]
No problems. Thank you for using and contributing optuna!

**Comment by Joelius300** [comment]
For better or worse, both import styles (`import lightning.pytorch` and `import pytorch_lightning`) are still supported, but they must not be mixed. Some up-to-date libraries are still using the old `pytorch_lightning` style which leads to conflicts when using them together with optuna because optuna uses the new `lightning.pytorch` style. I think the older libraries should update to the new style, but I wanted to write this here because there is more to this than "just use the new import". I will have to re-implement the `PyTorchLightningPruningCallback` because of this (luckily that's much easier than to re-implement the other library).
